# Automated Deployment of webapplication from Scratch in AWS.
---
- hosts: localhost
  become: "yes"
  gather_facts: "no"
  connection: "local"
  tasks:
  - name: Public facing VPC creation
    ec2_vpc:
      state: "present"
      cidr_block: "10.145.0.0/16"
      resource_tags: '{ "Environment" : "Dev" }'
      internet_gateway: "true"
      region: "us-east-1"
    register: pulic_ec2_vpc