# Automated Deployment of webapplication from Scratch in AWS.
---
- hosts: localhost
  become: "yes"
  gather_facts: "no"
  connection: "local"
  tasks:
  - name: Public facing VPC creation
    ec2_vpc:
      state: "present"
      cidr_block: "10.145.0.0/16"
      resource_tags:
        Name: "public_ec2_vpc"
        Environment : "Dev" 
      internet_gateway: "true"
      region: "us-east-1"
      wait: "yes"
      dns_hostnames: "yes"
      subnets:
        - cidr: "10.145.5.0/24"
          az: "us-east-1a"
          resource_tags:
            Name: "public_vpc_subnet"
            Tier: "web"
            Environment: "Dev"
      route_tables:
        - subnets:
            - "10.145.5.0/24"
          routes:
            - dest: "0.0.0.0/0"
              gw: igw
    register: pulic_ec2_vpc

  - name: set fact for vpc_id
    set_fact:
      public_ec2_vpc_id: "{{ pulic_ec2_vpc.vpc_id }}"
