# Automated Deployment of webapplication from Scratch in AWS.
---
- hosts: localhost
  become: "yes"
  gather_facts: "no"
  connection: "local"
  tasks:
  - name: Public facing VPC creation
    ec2_vpc:
      state: "present"
      cidr_block: "10.145.0.0/16"
      resource_tags: '{ "Environment" : "Dev", "Name" : "public_ec2_vpc" }'
      internet_gateway: "true"
      region: "us-east-1"
      wait: "yes"
      dns_hostnames: "yes"
    register: pulic_ec2_vpc

  - name: Print pulic_ec2_vpc info
    debug: var=pulic_ec2_vpc.vpc.cidr_block